from sqlalchemy import Column, Integer, String, Float
from models.base import Base

class StockModel(Base):
    __tablename__ = "stock"
    
    id = Column(Integer, primary_key=True)
    code = Column(String, unique=True, nullable=True)
    country = Column(String, unique=False, nullable=True)
    price = Column(Float, nullable=True)
    marketCap = Column(Float, nullable=True)
    numSharesAvail = Column(Float, nullable=True)
    yearlyLowPrice = Column(Float, nullable=True)
    yearlyHighPrice = Column(Float, nullable=True)
    fiftyDayMA = Column(Float, nullable=True)
    twoHundredDayMA = Column(Float, nullable=True)
    acquirersMultiple = Column(Float, nullable=True)
    currentRatio = Column(Float, nullable=True)
    enterpriseValue = Column(Float, nullable=True)
    eps = Column(Float, nullable=True)
    evToEBITDA = Column(Float, nullable=True)
    evToRev = Column(Float, nullable=True)
    peRatioTrail = Column(Float, nullable=True)
    peRatioForward = Column(Float, nullable=True)
    priceToSales = Column(Float, nullable=True)
    priceToBook = Column(Float, nullable=True)
    dividendYield = Column(Float, nullable=True)
    dividendRate = Column(Float, nullable=True)
    exDivDate = Column(String, nullable=True)
    payoutRatio = Column(Float, nullable=True)
    bookValPerShare = Column(Float, nullable=True)
    cash = Column(Float, nullable=True)
    cashPerShare = Column(Float, nullable=True)
    cashToMarketCap = Column(Float, nullable=True)
    cashToDebt = Column(Float, nullable=True)
    debt = Column(Float, nullable=True)
    debtToMarketCap = Column(Float, nullable=True)
    debtToEquityRatio = Column(Float, nullable=True)
    returnOnAssets = Column(Float, nullable=True)
    returnOnEquity = Column(Float, nullable=True)
    ebitda = Column(Float, nullable=True)
    ebitdaPerShare = Column(Float, nullable=True)
    earningsGrowth = Column(Float, nullable=True)
    grossProfit = Column(Float, nullable=True)
    grossProfitPerShare = Column(Float, nullable=True)
    netIncome = Column(Float, nullable=True)
    netIncomePerShare = Column(Float, nullable=True)
    operatingMargin = Column(Float, nullable=True)
    profitMargin = Column(Float, nullable=True)
    revenue = Column(Float, nullable=True)
    revenueGrowth = Column(Float, nullable=True)
    revenuePerShare = Column(Float, nullable=True)
    fcf = Column(Float, nullable=True)
    fcfToMarketCap = Column(Float, nullable=True)
    fcfPerShare = Column(Float, nullable=True)
    fcfToEV = Column(Float, nullable=True)
    ocf = Column(Float, nullable=True)
    ocfToRevenueRatio = Column(Float, nullable=True)
    ocfToMarketCap = Column(Float, nullable=True)
    ocfPerShare = Column(Float, nullable=True)
    ocfToEV = Column(Float, nullable=True)